### PR TITLE
replaced sphere-menu by 2D menu

### PR DESCRIPTION
**Pull request by tommuelli**
- Mixing 2D and 3D elements using a SubScene 
- SceneAntialiasing.BALANCED
- replaced sphere-menu by radion-button (styles)

### CODE REVIEW

**Comment by maxflow7934** [comment]
The changes are now on a branch of code of gotham. I had to pull in master...

**Comment by tommuelli** [comment]
So you merge it on (canoo) master later and I fetch from the master then ?

**Comment by maxflow7934** [comment]
Done.

**Comment by maxflow7934** [comment]
I changed the style a bit of the left navigation...

**Pull request merged**
